version: "3.8"

volumes:
  pgdata:

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
